CREATE TABLE HERMES_MI_STAGE.BOREPORTS (
    REPORT_KEY NUMBER NOT NULL, 
    REPORT_DESC VARCHAR2(250 BYTE) NOT NULL, 
    CONSTRAINT BOREPORTS_PK PRIMARY KEY (REPORT_KEY)
    USING INDEX 
    TABLESPACE HERMES_MI_DAILY
) SEGMENT CREATION DEFERRED 
COMPRESS FOR OLTP LOGGING
TABLESPACE HERMES_MI_DAILY ;


CREATE SEQUENCE HERMES_MI_STAGE.BOREPORTS_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    CACHE 10
    NOCYCLE 
    ORDER;


CREATE OR REPLACE TRIGGER HERMES_MI_STAGE.BOREPORTS_TRG 
BEFORE INSERT ON BOREPORTS 
FOR EACH ROW 
BEGIN
    IF INSERTING AND :NEW.REPORT_KEY IS NULL THEN
        SELECT BOREPORTS_SEQ.NEXTVAL INTO :NEW.REPORT_KEY FROM DUAL;
    END IF;
END;
/




CREATE TABLE HERMES_MI_STAGE.BOREPORTS_EMAIL (
    EMAIL_KEY NUMBER NOT NULL, 
    EMAIL_ADDRESS VARCHAR2(250 BYTE), 
    CONSTRAINT BOREPORTS_EMAIL_PK PRIMARY KEY (EMAIL_KEY)
    USING INDEX
    TABLESPACE HERMES_MI_DAILY  ENABLE
) SEGMENT CREATION DEFERRED 
COMPRESS FOR OLTP LOGGING
TABLESPACE HERMES_MI_DAILY ;


CREATE SEQUENCE HERMES_MI_STAGE.BOREPORTS_EMAIL_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    CACHE 10
    NOCYCLE 
    ORDER;

    
CREATE OR REPLACE TRIGGER HERMES_MI_STAGE.BOREPORTS_EMAIL_TRG 
BEFORE INSERT ON BOREPORTS_EMAIL 
FOR EACH ROW 
BEGIN
    IF INSERTING AND :NEW.EMAIL_KEY IS NULL THEN
        SELECT BOREPORTS_EMAIL_SEQ.NEXTVAL INTO :NEW.EMAIL_KEY FROM SYS.DUAL;
    END IF;
END;
/




CREATE TABLE HERMES_MI_STAGE.BOREPORT_DISTRIBUTION (
    REPORT_KEY NUMBER, 
    EMAIL_KEY NUMBER, 
    REPORT_GROUP NUMBER,
    CONSTRAINT BOREPORT_DISTRIBUTION_PK PRIMARY KEY (REPORT_KEY, EMAIL_KEY)
        USING INDEX
        TABLESPACE HERMES_MI_DAILY  ENABLE    
    CONSTRAINT BOREPORT_DISTRIBUTION_FK1 FOREIGN KEY (REPORT_KEY)
        REFERENCES HERMES_MI_STAGE.BOREPORTS (REPORT_KEY) ENABLE, 
    CONSTRAINT BOREPORT_DISTRIBUTION_FK2 FOREIGN KEY (EMAIL_KEY)
        REFERENCES HERMES_MI_STAGE.BOREPORTS_EMAIL (EMAIL_KEY) ENABLE
) SEGMENT CREATION DEFERRED 
COMPRESS FOR OLTP LOGGING
TABLESPACE HERMES_MI_DAILY ;


CREATE INDEX HERMES_MI_STAGE.BOREPORT_DISTRIBUTION_INDEX1 
ON HERMES_MI_STAGE.BOREPORT_DISTRIBUTION (EMAIL_KEY) 
COMPUTE STATISTICS 
TABLESPACE HERMES_MI_DAILY ;

