set lines 2000 pages 2000 trimspool on
set echo on feedback on termout on timing on 

spool T040_CREATE_TABLESPACES_results.lis

alter database datafile
'??:\mnt\oradata\ORACLE_SID\UNDOTBS01.DBF'
autoextend on MAXSIZE UNLIMITED
NEXT 100M;


CREATE TABLESPACE "CWMLITE" DATAFILE
'??:\mnt\oradata\ORACLE_SID\cwmlite01.dbf' SIZE 20971520 REUSE
AUTOEXTEND ON NEXT 655360 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "DRSYS" DATAFILE
'??:\mnt\oradata\ORACLE_SID\drsys01.dbf' SIZE 20971520 REUSE
AUTOEXTEND ON NEXT 655360 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "INDX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\indx01.dbf' SIZE 26214400 REUSE
AUTOEXTEND ON NEXT 1310720 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "ODM" DATAFILE
'??:\mnt\oradata\ORACLE_SID\odm01.dbf' SIZE 20971520 REUSE
AUTOEXTEND ON NEXT 655360 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "AURA" DATAFILE
'??:\mnt\oradata\ORACLE_SID\aura01.dbf' SIZE 2m REUSE
AUTOEXTEND ON NEXT 104857600 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "AURA_INDEX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\aura_index01.dbf' SIZE 1468006400 REUSE
AUTOEXTEND ON NEXT 104857600 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "CFA" DATAFILE
'??:\mnt\oradata\ORACLE_SID\cfa04.dbf' SIZE 104857600 REUSE
AUTOEXTEND ON NEXT 104857600 MAXSIZE UNLIMITED,
'??:\mnt\oradata\ORACLE_SID\cfa03.dbf' SIZE 2147483648 REUSE ,
'??:\mnt\oradata\ORACLE_SID\cfa02.dbf' SIZE 10485760000 REUSE
AUTOEXTEND ON NEXT 157286400 MAXSIZE UNLIMITED,
'??:\mnt\oradata\ORACLE_SID\cfa01.dbf' SIZE 10066329600 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "CFA_INDEX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\cfa_index02.dbf' SIZE 1073741824 REUSE
AUTOEXTEND ON NEXT 268435456 MAXSIZE UNLIMITED,
'??:\mnt\oradata\ORACLE_SID\cfa_index01.dbf' SIZE 4299161600 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "CFGLOG" DATAFILE
'??:\mnt\oradata\ORACLE_SID\cfglog02.dbf' SIZE 104857600 REUSE
AUTOEXTEND ON NEXT 104857600 MAXSIZE UNLIMITED,
'??:\mnt\oradata\ORACLE_SID\cfglog01.dbf' SIZE 4886364160 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "CFGLOG_INDEX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\cfglog_index04.dbf' SIZE 104857600 REUSE
AUTOEXTEND ON NEXT 104857600 MAXSIZE UNLIMITED,
'??:\mnt\oradata\ORACLE_SID\cfglog_index03.dbf' SIZE 104857600 REUSE
AUTOEXTEND ON NEXT 104857600 MAXSIZE UNLIMITED,
'??:\mnt\oradata\ORACLE_SID\cfglog_index02.dbf' SIZE 10485760000 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED,
'??:\mnt\oradata\ORACLE_SID\cfglog_index01.dbf' SIZE 4949278720 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "COA" DATAFILE
'??:\mnt\oradata\ORACLE_SID\coa01.dbf' SIZE 3879731200 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "COA_INDEX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\coa_index01.dbf' SIZE 2998927360 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "FTREG" DATAFILE
'??:\mnt\oradata\ORACLE_SID\ftreg01.dbf' SIZE 4540334080 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "FTREG_INDEX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\ftreg_index01.dbf' SIZE 2170552320 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "TAKEON" DATAFILE
'??:\mnt\oradata\ORACLE_SID\takeon01.dbf' SIZE 3827302400 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "TAKEON_INDEX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\takeon_index01.dbf' SIZE 1205862400 REUSE
AUTOEXTEND ON NEXT 104857600 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "USERS_INDEX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\users_index01.dbf' SIZE 7340032 REUSE
AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED
NOLOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "SNAPLOG" DATAFILE
'??:\mnt\oradata\ORACLE_SID\snaplog01.dbf' SIZE 104857600 REUSE
AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED
NOLOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT MANUAL;



CREATE TABLESPACE "UVDATA01" DATAFILE
'??:\mnt\oradata\ORACLE_SID\uvdata01.dbf' SIZE 1073741824 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "UVLOG01" DATAFILE
'??:\mnt\oradata\ORACLE_SID\uvlog01.dbf' SIZE 1073741824 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "ARCHIVE1" DATAFILE
'??:\mnt\oradata\ORACLE_SID\archive1.dbf' SIZE 524288000 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "UVLOG01_INDEX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\uvlog01_index.dbf' SIZE 524288000 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "UVDATA01_INDEX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\uvdata01_index.dbf' SIZE 524288000 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE "ARCHIVE1_INDEX" DATAFILE
'??:\mnt\oradata\ORACLE_SID\archive1_index.dbf' SIZE 524288000 REUSE
AUTOEXTEND ON NEXT 209715200 MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;

alter database datafile '??:\mnt\oradata\ORACLE_SID\users01.dbf' resize 40m;

alter database datafile '??:\mnt\oradata\ORACLE_SID\users01.dbf' 
autoextend on next 100m maxsize unlimited;

alter database tempfile '??:\MNT\ORADATA\ORACLE_SID\TEMP01.dbf' resize 10g;

alter database tempfile '??:\MNT\ORADATA\ORACLE_SID\TEMP01.dbf'
autoextend on next 1g maxsize unlimited;

create tablespace perfstat
datafile '??:\mnt\oradata\ORACLE_SID\perfstat01.dbf' 
size 2g autoextend on next 50m maxsize unlimited
logging online
extent management local autoallocate
segment space management auto;



spool off

