set lines 2000 pages 2000 trimspool on

spool recreate_xml_reports_table.lst


DROP TABLE "FCS"."XML_FATCA_REPORTS" cascade constraints;

CREATE TABLE "FCS"."XML_FATCA_REPORTS" (
    "XML_FATCA_REPORT_SEQ"  NUMBER(10,0)    CONSTRAINT "XML_FATCA_REPORTS_NN01" NOT NULL ENABLE,
    "LASTMODIFIEDDATE"      DATE            CONSTRAINT "XML_FATCA_REPORTS_NN02" NOT NULL ENABLE, 
    "LASTMODIFIEDUSER"      VARCHAR2(60)    CONSTRAINT "XML_FATCA_REPORTS_NN03" NOT NULL ENABLE, 
    "CREATEDDATE"           DATE            CONSTRAINT "XML_FATCA_REPORTS_NN04" NOT NULL ENABLE, 
    "CREATEDUSER"           VARCHAR2(60)    CONSTRAINT "XML_FATCA_REPORTS_NN05" NOT NULL ENABLE,
    "MESSAGEREF"            VARCHAR2(36)    CONSTRAINT "XML_FATCA_REPORTS_NN07" NOT NULL ENABLE, 
    "FATCAREPORT"           "SYS"."XMLTYPE" CONSTRAINT "XML_FATCA_REPORTS_NN08" NOT NULL ENABLE, 
    "FATCAREPORTSTATUS"     NUMBER(10,0)    DEFAULT 0 CONSTRAINT "XML_FATCA_REPORTS_NN09" NOT NULL ENABLE, 
    "FATCA_FILE_SUBMISSION_SEQ" NUMBER(6,0), 
    "PORTAL_STATUS"         VARCHAR2(100), 
    "XML_CLOB"              CLOB, 
    "MAJOR_VERSION"         NUMBER(3,0)     DEFAULT 0 CONSTRAINT "FATCA_FILE_SUBMISSION_NN10" NOT NULL ENABLE,
    "MINOR_VERSION"         NUMBER(3,0)
)    
--
-- Maybe needs "sys." on the next line. Maybe!
--
XMLTYPE "FATCAREPORT"   
XMLSCHEMA "http://hmrc.gov.uk/UKFATCASubmissionFIReport" 
ELEMENT "UKFATCASubmissionFIReport" 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING 
STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) 
TABLESPACE "UVDATA01" 
--
LOB ("XML_CLOB")        
STORE AS ( TABLESPACE "UVDATA01" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
);


CREATE  UNIQUE INDEX "FCS"."XML_FATCA_REPORTS_PK" 
        ON "FCS"."XML_FATCA_REPORTS" ("XML_FATCA_REPORT_SEQ" ) 
        PCTFREE 10 INITRANS 2 MAXTRANS 255 
        STORAGE(INITIAL 65536 FREELISTS 1 FREELIST GROUPS 1) 
        TABLESPACE "UVDATA01" LOGGING ;

        
CREATE  INDEX "FCS"."XML_FATCA_REPORTS_NX01" 
        ON "FCS"."XML_FATCA_REPORTS" ("FATCA_FILE_SUBMISSION_SEQ" ) 
        PCTFREE 10 INITRANS 2 MAXTRANS 255 
        STORAGE(INITIAL 65536 FREELISTS 1 FREELIST GROUPS 1) 
        TABLESPACE "UVDATA01" LOGGING ;

        
CREATE  UNIQUE INDEX "FCS"."XML_FATCA_REPORTS_UX01" 
        ON "FCS"."XML_FATCA_REPORTS" ("MESSAGEREF" ) 
        PCTFREE 10 INITRANS 2 MAXTRANS 255 
        STORAGE(INITIAL 65536 FREELISTS 1 FREELIST GROUPS 1) 
        TABLESPACE "UVDATA01" LOGGING ;

spool off;        