  -- 2 Roles for OEIC_RECALC 
  GRANT NORMAL_USER TO OEIC_RECALC;
  GRANT RESOURCE TO OEIC_RECALC;
  ALTER USER OEIC_RECALC DEFAULT ROLE RESOURCE;
  -- 2 System Privileges for OEIC_RECALC 
  GRANT CREATE SESSION TO OEIC_RECALC;
  GRANT UNLIMITED TABLESPACE TO OEIC_RECALC;
  -- 1 Object Privilege for OEIC_RECALC 
    GRANT EXECUTE ON FCS.TABLE_AUDIT TO OEIC_RECALC;
