  -- 3 Roles for ONLOAD 
  GRANT DATABASE_READER_UV TO ONLOAD;
  GRANT ONLOAD_ROLE TO ONLOAD;
  GRANT RESOURCE TO ONLOAD;
  ALTER USER ONLOAD DEFAULT ROLE ALL;
  -- 2 System Privileges for ONLOAD 
  GRANT CREATE SESSION TO ONLOAD;
  GRANT UNLIMITED TABLESPACE TO ONLOAD;
  -- 1 Tablespace Quota for ONLOAD 
  ALTER USER ONLOAD QUOTA 500M ON TAKEON;
