 -- 1 Role for UVSCHEDULER 
  GRANT NORMAL_USER TO UVSCHEDULER;
  ALTER USER UVSCHEDULER DEFAULT ROLE ALL;
  -- 2 System Privileges for UVSCHEDULER 
  GRANT AUDIT ANY TO UVSCHEDULER;
  GRANT CREATE SESSION TO UVSCHEDULER;
