
CREATE ROLE AIFMD_ROLE NOT IDENTIFIED;
CREATE ROLE BANKMANAGER_ROLE NOT IDENTIFIED;
CREATE ROLE BAP_APP_ROLE NOT IDENTIFIED;
CREATE ROLE CAPSIL_STP_ROLE NOT IDENTIFIED;
CREATE ROLE CAPSTOCK_EXPORT_ROLE NOT IDENTIFIED;
CREATE ROLE CASONLINE_ROLE NOT IDENTIFIED;
CREATE ROLE COMMS_ROLE NOT IDENTIFIED;
CREATE ROLE CRON_ROLE IDENTIFIED BY UTOPPD02123;
CREATE ROLE CVS_ROLE IDENTIFIED BY UTOPPD02123;
CREATE ROLE DATABASE_READER_UV NOT IDENTIFIED;
CREATE ROLE DATA_UPDATE_ONLY NOT IDENTIFIED;
CREATE ROLE DEALING_MANAGER_ROLE NOT IDENTIFIED;
CREATE ROLE DISCUSER NOT IDENTIFIED;
CREATE ROLE DISCUSER_REMOTE NOT IDENTIFIED;
CREATE ROLE DISC_ALL_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_CLIENTREL_MCRADM_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_CLIENTREL_MCRMGR_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_COMPLIANC_COMASS_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_COMPLIANC_COMSENASS_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FINANCIAL_MACASS_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FINANCIAL_MACDIST_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FINANCIAL_MACMGR_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FINANCIAL_MACSENASS_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FINANCIAL_MACSENCASH_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FINANCIAL_MACSENMGR_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FNDACCHUD_FADMADM_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FNDACCHUD_FADMMGR_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FNDACCHUD_FOPMGR_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FNDACCHUD_REGADCON_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FNDACCLON_FACCADM_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FNDACCLON_FACCMGR_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FNDACCLON_FOPADM_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FUNDOPERA_FOADM_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FUNDOPERA_FOMGRASS_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FUNDOPERA_FOMGR_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_FUNDOPERA_FOPADM_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_ITDEVHUDD_ALL_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_ITDEVLOND_ALL_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_ITDEVLOND_DEV1_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_ITDEVLOND_DEV2_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_ITDEVLOND_DEVMGR_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_MARKETING_AUDIT_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_NONE_COMMGR_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_NONE_FACCADM_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_NONE_FOADM_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_NONE_FOPADM_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_NONE_FOPMGRASS_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_NONE_PBSADM1_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_NONE_PBSMGRASS_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_OFFCESERV_OSMGRASS_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_REGISTER_REGADREG_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_SETTLEMNT_SETADM2_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_SETTLEMNT_SETADM_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_SETTLEMNT_SETMGR_ROLE NOT IDENTIFIED;
CREATE ROLE DISC_TECHSERV_TECHADM1_ROLE NOT IDENTIFIED;
CREATE ROLE EMAIL_AUTHORIZER NOT IDENTIFIED;
CREATE ROLE FATCA_BRIDGE_ROLE NOT IDENTIFIED;
CREATE ROLE FUND_MANAGER_ROLE NOT IDENTIFIED;
CREATE ROLE GPH_ROLE NOT IDENTIFIED;
CREATE ROLE IFA_MANAGER_ROLE NOT IDENTIFIED;
CREATE ROLE INVESTOR_MANAGER_ROLE NOT IDENTIFIED;
CREATE ROLE IOTERMINAL_ROLE NOT IDENTIFIED;
CREATE ROLE ISA_MANAGER_ROLE NOT IDENTIFIED;
CREATE ROLE LEEDS_CONFIG_ROLE NOT IDENTIFIED;
CREATE ROLE MI_ROLE NOT IDENTIFIED;
CREATE ROLE NORMAL_USER IDENTIFIED BY UTOPPD02123;
CREATE ROLE NORMAL_USER_NON_CONFIG NOT IDENTIFIED;
CREATE ROLE ONLOAD_ROLE NOT IDENTIFIED;
CREATE ROLE PLAN_MANAGER_ROLE NOT IDENTIFIED;
CREATE ROLE PRICING_ROLE NOT IDENTIFIED;
CREATE ROLE QUEST_SLP_201_USER NOT IDENTIFIED;
CREATE ROLE QUEST_SL_201_USER NOT IDENTIFIED;
CREATE ROLE QUEST_SL_60_USER NOT IDENTIFIED;
CREATE ROLE READONLY_ROLE NOT IDENTIFIED;
CREATE ROLE REMOTE_USER_ROLE NOT IDENTIFIED;
CREATE ROLE SALES_HISTORY_ROLE NOT IDENTIFIED;
CREATE ROLE SCHED_MANAGER_ROLE NOT IDENTIFIED;
CREATE ROLE SQLLOAD_ROLE IDENTIFIED BY UTOPPD02123;
CREATE ROLE SVC_AURA_SERV_ROLE IDENTIFIED BY UTOPPD02123;
CREATE ROLE SVC_DOCUMENT_CONTENT_ROLE NOT IDENTIFIED;
CREATE ROLE SVC_MONITORING_ROLE NOT IDENTIFIED;
CREATE ROLE SVC_PRICING_ROLE NOT IDENTIFIED;
CREATE ROLE SWORDFISH_ROLE NOT IDENTIFIED;
CREATE ROLE UV_APP_SUPPORT_ROLE NOT IDENTIFIED;
CREATE ROLE UV_CONFIG_MNGT_ROLE NOT IDENTIFIED;
CREATE ROLE WEBPORTAL_ROLE NOT IDENTIFIED;
CREATE ROLE WEB_USER NOT IDENTIFIED;
CREATE ROLE WKUSER NOT IDENTIFIED;
create user AALTOUNGARIAN_AURA identified by values '3CAC45BFC91A86D0' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user AAZIZ identified by values '9338678A0B6FE6B1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AAZIZ_AURA identified by values '45E1E448DF98B865' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user ABAJAJ identified by values '684DF878A4470339' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ABAJAJ_AURA identified by values 'F4D94A45062126EE' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ABONE_AURA identified by values 'F2ECBEA48F2DFAD1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ABRADSHAW1_AURA identified by values 'F5837B46D3A76DD2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ABROWN_AURA identified by values '746B9550E0A04ECB' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ACONNELL_AURA identified by values '8DA48FD1E23C5887' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ACOX2 identified by values '63C41F474E2C03B9' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ACOX2_AURA identified by values 'DF70AAC29B76CD30' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ACREARY1 identified by values '6769D33D8E2AD169' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ACREARY1_AURA identified by values '85DA8914D6A6912D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ACREARY_AURA identified by values '3076F1579E50CD8F' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user ADAMROBINS identified by values '01B4C8A28B6BB47A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ADEAN_AURA identified by values '2D61E0C3673A97BC' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ADELIOSTEVANATO identified by values '875FBAC84D4C164E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ADELIOSTEVANATO_AURA identified by values '0958F3C33E7A8210' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user ADODTI_AURA identified by values '30787181AE38297E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ADOHERTY_AURA identified by values 'A35B315A895AE346' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user ADUFFEY_AURA identified by values 'EEA88D1580B48175' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user AGULIN identified by values 'E2C872ECBBB1C163' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user AGUPTA2_AURA identified by values '6493B855B75D0AF2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AGURTHULA_AURA identified by values '697D0E95C02D3B6A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AHARKIN identified by values '99F72EEFB5C76E4B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AHARKIN_AURA identified by values '89B8040E2ED6B8AD' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AHEAD identified by values 'BF1BFA066ECDE854' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user AHUSSAIN1_AURA identified by values '7FF4DD43D3F6DCF6' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AIFMD_USER identified by values '5D001C6B35173D18' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user AJOHNSTON identified by values '3DEFBBD4E07E669D' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user AKAY_AURA identified by values 'B6EBDA5DA758A233' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ALBLAKEY_AURA identified by values 'E6BCC9C385165BFB' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ALEONARD_AURA identified by values 'DC2D0839F0BA560C' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user ALIMN_AURA identified by values '24833B4D3FD0A3AF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AMAHMOOD_AURA identified by values 'C25C3AADF2EF1DA0' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AMCCALLUM identified by values '51E17028A1A5877D' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user AMEANEY1 identified by values '43DAC1AB627D3D2B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AMEDOVARSZKI_AURA identified by values '39C0E68CFCD19E1A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AMIA_AURA identified by values '59A3F5CC0CAC6735' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AMISHRA_AURA identified by values 'D73A09AD6B61704A' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user AMITSIALIS_AURA identified by values '015D1F49AED09B1F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ANDREWBROWN_AURA identified by values 'F287A2BD9D621C66' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ANDREWTHOMPSON_AURA identified by values '7AA21DC446520BF6' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user ANNANEPOMNYASCHY identified by values '8576BDFE48AA2F43' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user AODRISCOLL_AURA identified by values 'B87F09E3334FD6B7' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user APALANDE_AURA identified by values 'D2E9972EEBDB92B5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user APATHIYALA_AURA identified by values 'A8652AE3D6056A55' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user APOLLARD_AURA identified by values 'F68B2F4D5BA057C5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AROBERTSHAW_AURA identified by values '55FDFE8473F137FE' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ASAPKALE_AURA identified by values 'F6246FB787BFA119' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ASHARMA1 identified by values '315FB867C8492998' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ASHARMA1_AURA identified by values 'E6D8563214A2D72C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ASHIRES_AURA identified by values '3960E6864C458D2B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ASHLEYCOLDWELL_AURA identified by values 'C17F09542DFD5FDE' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ASIDDIQUI_AURA identified by values '3DB7CBF5E8D3966E' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user ASINGH2_AURA identified by values '7B1A5FEB52C0AF72' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ASONDE_AURA identified by values '44C3CE56AB399EE8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ASPARKS identified by values 'F737E3951D74D67C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ASPARKS_AURA identified by values 'A8383B732B0B596B' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user ASUTHERLAND_AURA identified by values 'E95175409FB3DFCC' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user ATRIVEDI_AURA identified by values '8AD12CDAA057D0BC' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ATUCKER_AURA identified by values '25E6D45AC2114A07' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user AUDITU identified by values '7852DF64A61AC55A' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user AURA_ADMIN identified by values '02FD134C3C1334A8' default tablespace AURA temporary tablespace TEMP profile DEFAULT account unlock;
create user AURA_USER identified by values 'A5EDA930D991913B' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user AWAITE identified by values 'BBE095BD5EF10AE6' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user AWEBSTER_AURA identified by values '9ECFA8AFAFB66691' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user AWIACEK_AURA identified by values '893110D48AEC0F2B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BANKMANAGER_USER identified by values '49DA1C18788C0C02' default tablespace CFA temporary tablespace TEMP profile PRICING_PROFILE account unlock;
create user BBAPUSER identified by values '37447FA43024F000' default tablespace CFA temporary tablespace TEMP profile BAP_USER account unlock;
create user BBEDDOE_AURA identified by values '6728FFCDC15D5BD7' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user BBHUVA_AURA identified by values '8ECFCCEEEB6E0975' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BCOULSON_AURA identified by values '06DD6E2122911999' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BCRAVEN_AURA identified by values '38DB01E5DBDCADF4' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BDURAN identified by values '8D74EFEFBA153A04' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BDURAN_AURA identified by values 'EAB5B8EDF7D89C30' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BEDWARDS1_AURA identified by values 'BE6DFD0D21E3868C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BENKOTHE identified by values 'EAB5304974BE85B8' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user BGOKANI_AURA identified by values 'BF43DDF60673568A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BHILL_AURA identified by values '7684CDC242C75DCD' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user BHOWLETT identified by values '364365FA31A4AD85' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user BLEMAN_AURA identified by values '56151C66E9B84464' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user BMANSUKH_AURA identified by values '01BDCB6E48BFBF7B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BRASHID identified by values 'E412D5B9987F7B33' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BRASHID_AURA identified by values 'D5A587000F22AA0C' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user BRIANC identified by values 'B100850D571EED3B' default tablespace USERS temporary tablespace TEMP profile DEFAULT account unlock;
create user BTELFER identified by values 'B27C32B56C7DA2C1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BTELFER_AURA identified by values '583CF692A057C017' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BWADE identified by values '0E75C94A2902AAEB' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user BWADE_AURA identified by values '9929CAE76DFE0189' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CAGHA_AURA identified by values '196B965BA5CDB970' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user CAMBLER_AURA identified by values '4F820D09E6D3A8A0' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user CANDREW identified by values 'DBE88A30E6127AEE' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user CAPSIL_STP_USER identified by values '715FA065DF61123F' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user CAPSTOCK_EXPORT_USER identified by values '2D10B3D262A4BD9A' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user CASONLINE_USER identified by values 'F407CD2F7981E96F' default tablespace CFA temporary tablespace TEMP profile CASONLINE_PROFILE account unlock;
create user CBAGULEY_AURA identified by values 'B9942CBC003BEBCC' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CBALDWIN_AURA identified by values '3B6A7C689FF36796' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CBLAKEMORE_AURA identified by values 'FAB8260886B01442' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CBROWN3 identified by values 'E6DDAE7CC5845DC5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CBROWN3_AURA identified by values '6C0F4F2C15324BA4' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CBURROW_AURA identified by values '96DFC9A733D97588' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CCAMPBELL_AURA identified by values '38874D9998597E16' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CDCHAWLA_AURA identified by values '1ACB79822B95DBC2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CEASTWOOD_AURA identified by values '94FF974A2E14D142' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user CFERARU identified by values 'B8F42A8A38C39481' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CFERARU_AURA identified by values 'A26AED057D1B2037' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CFGWEB identified by values '9176B4BB46343EB3' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user CFGWEBPORTAL identified by values '83A3D72F2BE676DD' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user CFORBES_AURA identified by values 'C55CDF7971B864F8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CHOLDING_AURA identified by values '80A4CA2C973FA672' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CHRISTIANNEEDS_AURA identified by values '7418F7F76CDB7E18' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user CHUCKLE_AURA identified by values 'DE276DA9CF2051D8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CJAMES_AURA identified by values '0C0335AB7D5E7029' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CKENNEY_AURA identified by values '18370D0E544FD85A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CLEWIS_AURA identified by values '1D16BDC44894AC45' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CLOWRY identified by values '2B684E2D9CF481E1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CLOWRY_AURA identified by values '71BDE1EAA3EF3734' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CMTEMP identified by values '7ACAE695010ABFFC' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user CNEEDS_AURA identified by values '12687834C82DBCE8' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user COMMS_USER identified by values '93F061684E067501' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user CONEILL1_AURA identified by values 'D5737DA2F64959F5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CROBERTSHAW_AURA identified by values 'E96887D0B2A0BFC0' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user CRON_USER identified by values '3C6CC3BBB08DEB00' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user CSTOTT_AURA identified by values '6ED6FFF5ADBB4066' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user CVS_USER identified by values '7F5D037AECF5F446' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user DADAMSON_AURA identified by values 'F3FC97BE1A482FB7' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user DANCOBLE identified by values '628D8AB4AA50B092' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user DARRENWENGER identified by values '9636BE3FFD9873EE' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user DBA_AHARRISON identified by values '8AF634A2F64831D1' default tablespace USERS temporary tablespace TEMP profile DBA account unlock;
create user DBA_FALLDRITT identified by values '9FA29BCF1B9261AB' default tablespace USERS temporary tablespace TEMP profile DBA account unlock;
create user DBA_JVANKA identified by values '6C9BE47AFC741FB7' default tablespace USERS temporary tablespace TEMP profile DBA account unlock;
create user DBA_NFREEMAN identified by values '775E62F70F9DDDA5' default tablespace USERS temporary tablespace TEMP profile DBA account unlock;
create user DBA_NLADVA identified by values '6DF32CB36B9B5016' default tablespace USERS temporary tablespace TEMP profile DBA account unlock;
create user DBA_SGRAY identified by values '3AE8C82CF547A20B' default tablespace USERS temporary tablespace TEMP profile DBA account unlock;
create user DBOOTHROYD_AURA identified by values '3C2924ACA81D978A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DBRENNAN_AURA identified by values 'AF7BE04F602C38C3' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DBURGESS_AURA identified by values 'F29FDE2676D21751' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user DBURKE_AURA identified by values '634C6A046A81D9A9' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user DCOWDEROY_AURA identified by values 'E186336B607CEE55' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user DDAWSON_AURA identified by values 'F5E411E7E8A9B52A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DEALING_MANAGER_USER identified by values '33B46846136B7811' default tablespace CFA temporary tablespace TEMP profile DEALING_MANAGER_PROFILE account unlock;
create user DFENTEMAN_AURA identified by values '86C07044C98D1F30' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DGROOM2_AURA identified by values 'CFBE61D8B3C2123B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DHARVEY_AURA identified by values 'ECA5347850EBF960' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DHEELEY_AURA identified by values '70D13E0723ABC9D1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DHOLLAND identified by values 'C9D97F85852EDACF' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user DISCADMIN identified by values '237DB4F85C8941A5' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user DISCBATCH identified by values 'F2BCA8CC61E6E0CF' default tablespace USERS temporary tablespace TEMP profile DEFAULT account unlock;
create user DJOSE_AURA identified by values '08DC434EBB24CB74' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DKUMBHAR_AURA identified by values '1793F1B13ABF1A91' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DLAKE identified by values '3C1439137BD433B9' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user DLEIGHTON_AURA identified by values '21F756DBCB0403EE' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DLLEWELLYN_AURA identified by values 'AF1E6749B47B984A' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user DMALONE1_AURA identified by values 'C3630BB3BE955ABA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DPATIL1_AURA identified by values 'C3C73924830CEAE2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DPHILLIPPO_AURA identified by values 'B42A01B80741C9C9' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DSINGH_AURA identified by values 'B798C5CED8A7D2B7' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DTHOMAS identified by values 'DBCD0A1B760CA689' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user DWOOD1_AURA identified by values '0E2A59A0E7AA22E6' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DWOOD_AURA identified by values '541A8668F4E53B58' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user DYEBOAH_AURA identified by values '2480ADF1C6618627' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user EDATE_AURA identified by values '27CA311D22ED27FF' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user EHOLT_AURA identified by values 'A48B18EBA816674D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ELODGE_AURA identified by values '52C782E086F86A1D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user EMOLOKWU_AURA identified by values '887A9B2F8325598D' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user EMX_USER identified by values '18B23C43DA050F04' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user ESAVAGE_AURA identified by values '68B0395E9CE856AC' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ESMITH identified by values '1ABB3413CA02E754' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user FATCA_BRIDGE_USER identified by values '0291581248909639' default tablespace CFA temporary tablespace TEMP profile SERVICE_USER account unlock;
create user FCS identified by values '3BD0F38FADB20E8C' default tablespace UVDATA01 temporary tablespace TEMP profile DEFAULT account unlock;
create user FDONLAN_AURA identified by values '5294FD6DC28A4995' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user FDRAFZ_AURA identified by values 'C56FB3A1A166A7C5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user FGILLOTT_AURA identified by values 'CFCDBB6CAF0EF1AF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user FHOLLAND_AURA identified by values '4ED3DD6C77CE7154' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user FKARNELIA_AURA identified by values '77EDFC1025957ED2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user FMALIK_AURA identified by values '2CC6A7E563C5002F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user FROBERTS identified by values '4E563DA4AC897E9C' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user FUND_MANAGER_USER identified by values 'A9B1BA8CF6A2C6BE' default tablespace CFA temporary tablespace TEMP profile FUND_MANAGER_PROFILE account unlock;
create user GBAMFORTH_AURA identified by values '6E4F5172565112F7' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GCROSSLEY_AURA identified by values '982E9A4B102AF92C' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user GCUMBERLAND_AURA identified by values 'A90E04BBF0CC6729' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user GGAREWAL_AURA identified by values '91F950CA6F01BF3D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GHARTLAND_AURA identified by values '95FEB2565D3E788D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GHIPKIN identified by values '94E8DFCADB36744D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GHIPKIN_AURA identified by values 'AD88E891128A9F6E' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user GILLIANSPENCER_AURA identified by values 'DADB73152E891C38' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GJCAIN identified by values 'EE90542B96847E72' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GJCAIN_AURA identified by values '5C7D17A80B230D09' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GLENNCROSSLEY identified by values '80C5A90192183DC8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GLENNCROSSLEY_AURA identified by values 'E4E48FF940F2D105' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user GPH_USER identified by values 'BFCD4899E59A87BC' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user GSHAH_AURA identified by values '3382249E16B2F820' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GSHIPP_AURA identified by values 'E85D19EAC294A511' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GSHUKUROVA_AURA identified by values '3E60F0FAFA21410F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GSODEN_AURA identified by values '78A4672A0692C76B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user GTAIT identified by values '045CB15AB4DDE58E' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user GYOUNG identified by values '7E21C94D4E427C56' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user HANSARI_AURA identified by values '11760B8BEE3F5752' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HBIBI identified by values '01FD6A3397B7BC2C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HBIBI_AURA identified by values '4D4DD6654D659B3F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HCRAIG identified by values '266E616812F7A4FB' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user HDAVIS identified by values '3466406ABBDD4E93' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HDAVIS_AURA identified by values '49D46DAC76FD63CE' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HGEALE_AURA identified by values '9F61BF4A91E4ECDD' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HKAUR_AURA identified by values 'B78CE6C62BC82A3F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HKHAN identified by values 'A7D9890DB0B5F9CF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HKHAN_AURA identified by values '4E5D4428608B45D1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HKIRAN identified by values '579C3388213AE266' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HKIRAN_AURA identified by values '9384CDECD6D0D804' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HKOWALCZYK_AURA identified by values '8DD4FD0798B8B052' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HLEATHERDAY_AURA identified by values 'A17548A0045DD6DB' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HMASSEN_AURA identified by values 'C08100E36A5A126B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HOZA_AURA identified by values 'E368EC7C0C2DBEFA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HPARSON identified by values '86CCFA60D85EB616' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HPARSON_AURA identified by values 'CAE3E59A4A684B42' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HPOOJARY_AURA identified by values '35D7A692D24BB2DE' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HPOOJAY identified by values '1F3B0E9FF2FDF2EA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HPOOJAY_AURA identified by values 'A507036925F1EAAF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user HSBCREMOTE identified by values '38C05A0C35E05227' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user IBAKER_AURA identified by values '461F993536230721' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user IBASHIR identified by values '44D03E43502658BE' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user IBASHIR_AURA identified by values '65959F7FDE548764' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user IBURROWS identified by values 'C517324A1A1C6EDA' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user IFA_MANAGER_USER identified by values 'E658E2F818A2D803' default tablespace CFA temporary tablespace TEMP profile IFA_MANAGER_PROFILE account unlock;
create user IGARNER_AURA identified by values 'F4382AD53852E272' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user IKHAN2_AURA identified by values '1B0CFE3026571B6C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user IMOSES_AURA identified by values '01AE0D528E9CCB51' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user INVESTOR_MANAGER_USER identified by values '284FEF33725F3BF6' default tablespace CFA temporary tablespace TEMP profile INVESTOR_MANAGER_PROFILE account unlock;
create user IOTERMINAL_USER identified by values '9797A49AB317DE34' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user ISA_MANAGER_USER identified by values 'FFCCA6DCF6F4AE7C' default tablespace CFA temporary tablespace TEMP profile ISA_MANAGER_PROFILE account unlock;
create user ITOPS identified by values '2DD9A863242E95E8' default tablespace USERS temporary tablespace TEMP profile DEFAULT account unlock;
create user JAPPLETON1_AURA identified by values '6A28BFB58BF02748' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JBICKLER_AURA identified by values '9E42F09BCC8B96F9' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JBLACK identified by values 'DC5639F96FEF4E54' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JBLACK_AURA identified by values 'D89D45E78B107755' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JBRADLEY identified by values '7F060446BEA400C5' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user JCASTLE_AURA identified by values '17846E5052BF660A' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user JCHURCH_AURA identified by values '90BF2B8D11BF90C1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JCULLEN1_AURA identified by values '7983EA8668159F63' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JDONNELLY_AURA identified by values '79499325518BF3C1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JDONNE_AURA identified by values '9C107FF3E24B474A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JEASTWOOD_AURA identified by values '60FDF176CF2CB42A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JFISHER_AURA identified by values '4AD87E966F77163C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JFORSTER_AURA identified by values '30E34F31B3F23E61' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JFRANCE_AURA identified by values 'D2548746D787B7C0' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JGAMBINI_AURA identified by values '90CDC82BA395F1C2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JGRIFFIN_AURA identified by values '22E5FE6C8495F24A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JGUGAS_AURA identified by values 'EC2F4DEC105064B1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JHOLMES_AURA identified by values '158CAA83942E3AC2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JJOSHI_AURA identified by values '4F56B1E710EEE25A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JKEENAN_AURA identified by values 'BF24DD932B25E636' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JKEY identified by values '5149AEBD1DBDC3E5' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user JKOSZULINSKI_AURA identified by values '95A51FB749908719' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JLAPPAGE_AURA identified by values '234E085CFA84C590' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JLEWIS identified by values '95887C56AEEEDAE5' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user JLONGHORN_AURA identified by values '5674F1635B526D97' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JMILLS_AURA identified by values '84B21D596ACB025E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JMOORE identified by values 'A4B9B2372C30EE41' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JMOORE_AURA identified by values 'C294E2FD0CC33897' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JMORRISON1_AURA identified by values '63A0E4BADC5DF98D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JODONNELL_AURA identified by values 'FC91E748E32C2991' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JOHNNORRIS_AURA identified by values '2558B29AB1F72482' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JOHNODONNELL_AURA identified by values '3889902D013D66E0' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JOVERAL identified by values '7B059BD9C49BB4BF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JOVERAL_AURA identified by values '1BE9FAC9B25B476A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JPRUDHOE_AURA identified by values 'AF24D72D0759FB4E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JRICE1_AURA identified by values 'B27FAED9C8DB8DDA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JRICHARDSON1 identified by values '7FC0559AFE022EED' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user JRIDDICK identified by values 'ED15B3443368CFA2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JRIDDICK_AURA identified by values 'DFDC63A402F4C9BE' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JSHAW_AURA identified by values '7324069A3D5BD8B4' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JSTEPHENS_AURA identified by values '5952E347DBF7BFBA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JSTEVENSON identified by values 'D12E117E44ACCC17' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user JSTOCKS_AURA identified by values 'EE10A1917565A4B3' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JSWAISLAND identified by values '775D15A0D327F86D' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user JTHEBAULT_AURA identified by values '674394390731C2B7' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JTHOMPSON2_AURA identified by values '1B3997837729A0FA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JTINSON identified by values '116123AB00A44419' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JTINSON_AURA identified by values 'CCA8350D66610FBA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JVONG_AURA identified by values 'D711E6F991F872ED' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JWALDRON_AURA identified by values 'C22DC078ED4E0129' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JWELLS_AURA identified by values '76618B23F86570C4' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JWHITCHON identified by values 'BE264D01E612161E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user JWHITCHON_AURA identified by values '25B97F5BBB57E19F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KAGBAVOR_AURA identified by values '9178AFA98731F289' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KATIEBILODEAU identified by values '4FA1B4C55A266F65' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user KBEUSMANS_AURA identified by values '6158C266B798F557' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KBOWLER_AURA identified by values 'F0DDB87A319456CA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KBROOKE_AURA identified by values '6E89DB4A1847A7C8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KBROWN_AURA identified by values 'E022F2E9C99144A6' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KDALVI_AURA identified by values '24E345116F6456F0' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KDHOLAKIA_AURA identified by values '7AC257201C3B6AB8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KEVINBAILEY_AURA identified by values '6D558C3A8EDEA03B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KGOTT_AURA identified by values '8736DE4E1A63747D' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user KHENNESSY identified by values '6B775DC0A2E1DCAD' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KJAWALKAR_AURA identified by values '0D92E5A6DB9243D5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KJOGI_AURA identified by values '9032DE5241246EED' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user KLIU_AURA identified by values '9ADFA451CEB639D1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KMAYGER identified by values 'C463BF817CADF57E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KMOOKAN_AURA identified by values '94045312B3B18943' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KPARK_AURA identified by values 'EE6B0F8A236B76FF' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user KSHARIF_AURA identified by values 'F257D50CCEA50765' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KSHURETY_AURA identified by values '96B04427125D47F9' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user KSONEJI_AURA identified by values '5EAE8533F6C39511' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KSPEIGHT_AURA identified by values 'FB85FDD3FF873A60' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KTALREJA_AURA identified by values '34948C8E857EEE8F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KTO_AURA identified by values '62E9A7FFCB0DF898' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KTURNER_AURA identified by values '7243FA79D4B73DFA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KVAISHAMPAYAN_AURA identified by values '7C51ED5558016C20' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KWILSON1_AURA identified by values '85804EB22D0FE037' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user KWILSON2_AURA identified by values 'F6808E7964CE87C5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user LALEXANDRESCU identified by values 'A19AC74867EDAB12' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user LALEXANDRESCU_AURA identified by values 'BAC98E4CDD3F638A' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user LBARKER_AURA identified by values 'A251483000D69282' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user LBRADY_AURA identified by values 'B2304761486667D0' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user LDELANEY1_AURA identified by values 'BF8A03AEA6102F03' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user LDRIVER_AURA identified by values 'BB57FF927EFDF45A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user LEEDS_CONFIG identified by values '9C7B27D7D68FA027' default tablespace USERS temporary tablespace TEMP profile LEEDS_CONFIG_PROFILE account unlock;
create user LEEWOODCOCK_AURA identified by values 'F234E80626811316' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user LGARDNERBROWN identified by values '943D3D3ADF266877' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user LGREENWOOD_AURA identified by values '8550100A491B15E4' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user LHALTON identified by values 'C0BF51F81D0492E0' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user LINDAPEARCE_AURA identified by values '5CC66D97349811FC' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user LMHOLT_AURA identified by values '3EC20DC533E4065B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user LPARKER identified by values 'B64D50F1889B1141' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user LPARKER_AURA identified by values 'EA63BE0F52361F03' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user LSTOKES_AURA identified by values '62FEAA01F604883C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user LTAYLOR identified by values 'FA1F3C0BBF7B41E9' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user MABELI_AURA identified by values 'D8D1C0C14F2736A3' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MARTINSYKES_AURA identified by values 'DD644BF05C9ADF0C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MARTINWELLS_AURA identified by values '6D6505BA37661D0F' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user MARTINWILLIS_AURA identified by values '3167E4AAFB8D024B' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user MATAYLOR identified by values '7EC686F95D88878A' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user MATKINSON_AURA identified by values '9DD18FB4C6F5F6F5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MATTHEWGREGORY_AURA identified by values '28E5E3AB13766357' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MBOTTOMLEY_AURA identified by values '1FC0A97E8DAE0AB3' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MBROADBENT_AURA identified by values '240DDA7DC95B6DB5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MBROWN1_AURA identified by values '05C78F89CE40EF97' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MBUTLER1_AURA identified by values '771481E0C856D3B3' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MCREDLAND_AURA identified by values '7838DC609F4DA3F4' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MDOYLE_AURA identified by values '5C8FB7564752346C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MDRIFFIELD_AURA identified by values 'F768750FF9E3B2F9' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user MFERRARI_AURA identified by values 'BF664FD9D322E3FC' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MGEDULT identified by values '033FA06A5A832775' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user MGIALI identified by values '0FDCCD4229037FA4' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MGIALI_AURA identified by values '9B04CBC4E799E578' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MGREEN2_AURA identified by values '601ABEAAA605C2E0' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MGRUNDY identified by values '1E93C2195A87EC59' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MGRUNDY_AURA identified by values '7EDE218DC979D228' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MHALL_AURA identified by values '8C5B1FFBD27F1E00' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user MITAYLOR identified by values '04D8ADA24AAB37C4' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user MI_USER identified by values '58FD33CE5F960410' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user MKENNARD identified by values 'F9383057AECC2CF4' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user MMOSS_AURA identified by values '499C93AB7C3BCCEF' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user MPANCHAL_AURA identified by values '57532CFE71B83AB9' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MPATTISON_AURA identified by values 'C7028F2C8711AF1F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MPENN_AURA identified by values 'EF5BA09F302A8EB7' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MPHILLIPS identified by values '000DDFCE0FE8EDC2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MPHILLIPS_AURA identified by values '5D01A2C946CBD561' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MPOOJARY1_AURA identified by values 'F7591D2465998170' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MPROUDFOOT_AURA identified by values 'DC2589D9D10C60A1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MRABY1_AURA identified by values '4133F4B66C3CB262' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MRAJWANI_AURA identified by values 'CEE1C8C88C815458' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MRICHARDSON_AURA identified by values '2514B09D65B1AC1D' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user MSIMON_AURA identified by values 'E6E48C7DD98071B6' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MSOBOLEWSKI_AURA identified by values 'BCE0BB6D15F5DC4A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MTAYLOR1_AURA identified by values '412082778A23F95D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MTOOLAN_AURA identified by values 'FD7BA54C2641812C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MWATERHOUSE_AURA identified by values '301EC558B54AAA2D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MWEIR_AURA identified by values 'DE3A4B76ABC18B67' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MWELLS_AURA identified by values '852DDF67D7C43B8A' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user MWHUSSAIN_AURA identified by values '10E049C298426C07' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MWLADZINSKA_AURA identified by values '5B128C2F5CAE97BA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MWRIGHT identified by values 'B1195F02A5CE4376' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user MWRIGHT1_AURA identified by values 'F3C40E90718ED8F2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user MYARBOROUGH_AURA identified by values 'A56F4972A4015048' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user MYLESFEARNLEY_AURA identified by values 'A15E929356E7D8B7' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NATALIERICHARDSON1_AURA identified by values '0ABFD9C647336464' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user NATALIERICHARDSON2_AURA identified by values 'E2BAACF342BAEF8B' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user NATHAN_AURA identified by values 'D915A7884FA43261' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NBHADRA_AURA identified by values '7F1C7D568AEC6B37' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NBINSTED_AURA identified by values '6EDCB824B0F0D7F8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NDEAN_AURA identified by values '2AA303D9FC02BA42' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NDICKENS_AURA identified by values '05EEAB4E1E0229B1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NEPTUNE identified by values '998F344FB8420BAE' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user NFREEMAN identified by values 'F1107CE4ADEDFAED' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user NICHOLAJACQUES_AURA identified by values 'C4F78FC46DEE1015' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NICHOLASLOTT_AURA identified by values '18C6F507A251E171' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user NICKHALL_AURA identified by values 'FD391A23154E81A3' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user NKHERA_AURA identified by values '88C45DA6A62C7CD5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NKIRBY1_AURA identified by values 'AD4FEC00C6FE9340' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NLADVA identified by values '78F77F65588DE3EA' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user NLJESSON_AURA identified by values '39DB8E6CE5D608C5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NLOTT_AURA identified by values '50E6A7BFF7A924D6' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user NMANERIKAR_AURA identified by values '2537DFB41C75CC4F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NMARATHE_AURA identified by values '135F3528546ACDD6' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NMUDD_AURA identified by values '80ACA838EB4B6FDA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NRASHID_AURA identified by values '42E9C5C916A1E35D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NRONCHETTI_AURA identified by values 'FE0F9BD72F7DA6FD' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user NSENIOR_AURA identified by values '33AFF41534A4E6F2' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user NSHARIF_AURA identified by values '94EDCBCFE378EE48' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user OBENNETT_AURA identified by values 'FBAA75B27F722437' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user OEIC_RECALC identified by values '08F2E1B5CB93F274' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user OGRICE identified by values 'B4241292D369B2DF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user OGRICE_AURA identified by values '1267D70BF9A9346E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ONLOAD identified by values 'B084F4B16F4BD3CA' default tablespace TAKEON temporary tablespace TEMP profile DEFAULT account unlock;
create user OPS$UADMIN identified by values 'EXTERNAL' default tablespace USERS temporary tablespace TEMP profile DEFAULT account unlock;
create user PAULBURNS_AURA identified by values '2A9B5271F270C34E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PAULMALLINSON_AURA identified by values '78AB6533518E7559' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PBARASKAR_AURA identified by values 'B71A23C713CAB305' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PBIENIA_AURA identified by values '83654BF161F2525E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PBROWN identified by values 'E11B7BED552607C1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PCOLLINS identified by values '7D28DD549D5FE17F' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user PDIAMOND_AURA identified by values '339E49371C8B5C00' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PDIXIT_AURA identified by values '6D73855E04E10469' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user PHANCOCK1_AURA identified by values '34FE9F9A65BDCE2E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PHARRISON_AURA identified by values '0C8EC808CEF1A84A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PJAIN_AURA identified by values 'B8B557D2131E362A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PJAISWAL_AURA identified by values '457C3025EC5904C1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PKAMBLE1_AURA identified by values '1D1CC6CA7C99F646' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PKAPOOR_AURA identified by values 'EF98B3152CBA468E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PKHIMANI_AURA identified by values 'D5066BF143924210' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PLAMBERT_AURA identified by values '843E944CEF0AC04D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PLAN_MANAGER_USER identified by values '3C05EB23620D2E87' default tablespace CFA temporary tablespace TEMP profile PLAN_MANAGER_PROFILE account unlock;
create user PLINEHAN_AURA identified by values '01FCB2A4EE1C394A' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user PPANCHMUKH_AURA identified by values '2A6D6F24577D45A0' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PPHILLIPS identified by values 'CEC73B1BE68C40CC' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PPHILLIPS_AURA identified by values '065A9B7A28967DFB' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user PPRABHU_AURA identified by values '0595333D1425E22B' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PRICING_USER identified by values '3A566F31F2761C1A' default tablespace CFA temporary tablespace TEMP profile PRICING_PROFILE account unlock;
create user PROBSON identified by values 'A2AAFE6C697A4E30' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user PSAHU_AURA identified by values '5C47DD70B8126309' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PSHARDUL1_AURA identified by values '5568E302E3DC16DE' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PULLAL_AURA identified by values 'EA3CF8DF5FDE8654' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user PZAMULINSKYJ_AURA identified by values '2FD10400E5ABA844' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RANJANISULUR identified by values '578122BE0617FF11' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user RBAJETHA_AURA identified by values 'BFA7A120BAFFEBC4' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RBEVIN identified by values '64C19FBA467072D3' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user RCHAURASIA_AURA identified by values '0DE941E32D1978E8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RDOCTOR identified by values '4499E55AA71EBDE5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RDOCTOR_AURA identified by values 'A953A5A6C08360EF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RDOYLE_AURA identified by values '577FD1547277A811' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RGANDY1_AURA identified by values '3521690279FD0F05' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RGASKELL_AURA identified by values '59CDDE90E1818F1E' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user RGILMOUR_AURA identified by values '438A09C25ED4D897' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RGRANT_AURA identified by values 'E3C0886A95A17B4E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RHALEY_AURA identified by values '3EF4A1EAA582F251' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RKUMAR_AURA identified by values '3861EE0A00A8D71E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RMCCLARY_AURA identified by values '536EB8CC8EDF2887' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user RNAIR1_AURA identified by values 'A14EDEBEC770EC03' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ROBERTNAIR_AURA identified by values '2140D1DC69797D18' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RPANCHOLIA_AURA identified by values '83AE8C786F19A595' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RPATIL_AURA identified by values 'C3306EF426E037B6' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RPINDER_AURA identified by values '606B39911009E36F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RRAINEY_AURA identified by values '704CD9F92B12BA3D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RREYNOLDS_AURA identified by values '528B7A5C67F629FC' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RSINGH_AURA identified by values 'F0411C47B4818878' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user RTARAL_AURA identified by values '4EAE11CB59CD2E67' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RTURNER1 identified by values '1F659B292E5E0A0F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RTURNER1_AURA identified by values '0037BC638D6F5A31' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user RWARD_AURA identified by values '18B2F80D79537B7E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SALI3 identified by values 'B687A266BE1F4EE4' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SALI3_AURA identified by values 'C58886A787EA4963' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SAPPLEBY identified by values 'EF7147ED6F1ED333' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SASLAM_AURA identified by values '24C2939216905E25' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user SBAGAL_AURA identified by values 'E7F101A4F3D938BF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SBAJWA_AURA identified by values '0BCDE6E5378ED42F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SBENKALKAR_AURA identified by values '0B629C5CD497DF77' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user SBENNETT_AURA identified by values '55AF167A6392A33E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SBOAKYE_AURA identified by values '10FF13149C8952A3' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SBURTON identified by values 'CDC68187F4AFAD68' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SBURTON_AURA identified by values 'DD3B8FAE20E38230' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SCALLOW identified by values '4D6126FFBB296D9E' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user SCHAPEKAR_AURA identified by values '3C5683999B978094' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SCHATUR_AURA identified by values 'C5A97DA7577345AB' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SCHEDULER_TASKMANAGER identified by values '7131BE042EB5CB75' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user SCOTTHARRIS identified by values 'BE3CBE584A89B9E5' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user SDHEBE_AURA identified by values '4AA30404B9844693' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SDOHERTY_AURA identified by values '6D472445CE1AD4CB' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SDREWETT identified by values 'E5B9AF481ED0E8CF' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user SDUNN identified by values '61882906D3B296B8' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user SGEARY1_AURA identified by values '536378FDCE1BE898' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SGHAFOOR_AURA identified by values '260C193A88B3AA6F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SGRUMMETT_AURA identified by values '7D51796B43D0F7D9' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SHEPWORTH identified by values '17165BC69C409045' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SHEPWORTH_AURA identified by values '9C4E381C287C1615' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user SHOUGHTON_AURA identified by values 'AB17BF9D0DDB6F02' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SHUSSAIN1 identified by values '4589C9C209AEB1F4' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SHUSSAIN1_AURA identified by values '2039C2D9AAA6E2B8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SJOWETT_AURA identified by values 'C5DD0A2FB1298D1D' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SKAPOOR identified by values 'DE52700D339BEB9A' default tablespace USERS temporary tablespace TEMP profile DEFAULT account unlock;
create user SKHAN4_AURA identified by values '65C8178EF71BF5DD' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SKHAWAR_AURA identified by values '2E3FF21A776B5AFD' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SLALL_AURA identified by values '4366DBA574A62CD1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SMAHALA identified by values '1FEC75530EDAECAC' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SMAHALA_AURA identified by values 'B36704294A45A857' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SMANKIN_AURA identified by values 'A85FFFA1BDC58148' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SMATTHEWS identified by values '0A2CC9CAAA464879' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user SMEHAT_AURA identified by values 'C96E86296AEEB593' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SMORLEY_AURA identified by values 'F82EED7EAF936FF1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SMOSES_AURA identified by values '6267CA315970AB0A' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user SNAIR1_AURA identified by values '4DB330B49C094064' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SNIDISH_AURA identified by values '25DE16B87EEEA8CF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SOCONNOR_AURA identified by values '35F11558F9B6F0A3' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SPARKINSON identified by values '2E8797B75E7F35AA' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user SPURSSELL_AURA identified by values 'F57DDB20D7834AFF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SQLLOAD_USER identified by values '88BDA71766FA5F15' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user SRAJEBHOSLE1_AURA identified by values 'AD043A0A31CA5BC1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SRAZZAQ identified by values '472BE897CBC2641E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SRAZZAQ_AURA identified by values '29F9AE6D05E21639' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SROWLEY_AURA identified by values 'F7D523FCACF71F0C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SRVDEVMON identified by values '27360734E6E599A7' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user SSAGU_AURA identified by values 'E2B6F1C3E22C1DF7' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SSALVE_AURA identified by values '64757DD12037E21F' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SSHRESTHA2_AURA identified by values '14E5391E7B86AC59' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SSTRINGFELLOW_AURA identified by values 'C62D80E9CF52BDFB' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SSUBRAMANIAM_AURA identified by values '406FEBA37C8252D1' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user SSUHAN identified by values 'AD3D84108B96B6E8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SSUHAN_AURA identified by values 'C2044C36DF56D615' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user SSUNDARESWARAN_AURA identified by values '2A9B01504DCD32EE' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user STAMUR_AURA identified by values '9F23B60525139334' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user STHIK_AURA identified by values 'D725BF05B8C6EC01' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user STPUSER identified by values '487B441BA691C95D' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user STUARTMORTON_AURA identified by values '3128672CD2CF17B8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SVC_AURA_SERV identified by values '360E78B01EE00B2A' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user SVC_DOCUMENT_CONTENT_USER identified by values 'DC8C9B19EEB04B86' default tablespace CFA temporary tablespace TEMP profile SVC_DOCUMENT_CONTENT_PROFILE account unlock;
create user SVC_MONITORING_USER identified by values 'F95CFA6D626F8D0D' default tablespace CFA temporary tablespace TEMP profile SVC_MONITORING_USER account unlock;
create user SVC_PRICING_USER identified by values 'CAAA5A1F5E3EA006' default tablespace CFA temporary tablespace TEMP profile SVC_PRICING_USER account unlock;
create user SVICHARE_AURA identified by values '9DB326D6EDD12E99' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SWHITEHOUSE identified by values '44A5750BCDD14EC6' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SWHITEHOUSE_AURA identified by values 'F0522CD557B699F5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SWILKS identified by values '6BC9B42EC2A0125F' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user SWORDFISH identified by values 'F1502A0B495ABE55' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user SWORSWICK identified by values '55A5C33148D3C5B8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SWORSWICK_AURA identified by values '416FEDC9A44BB354' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user SYATES_AURA identified by values '5AF385C481F8C7B8' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SYIN identified by values 'E5E5B17407C21206' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user SYIN_AURA identified by values 'C0A15A52D179AE98' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user TBRADLEY_AURA identified by values '9BCF84788818CC24' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user TBROWN1_AURA identified by values 'A299AF90FB11423A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user TBURNS_AURA identified by values '0D4D1F277B819D25' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user TCHANTER identified by values '697B3695B6AEF5A4' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user TDALEY_AURA identified by values '75C96AAD16AEA7CD' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user TDUTTA_AURA identified by values '47AE91FC903765EA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user TESCOTT_AURA identified by values 'B6B24761D3C7E76E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user TGOLDTHORPE_AURA identified by values '6C25A146FB4638AA' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user TGOODWORTH_AURA identified by values '734F22E5354D8E78' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user THARE identified by values '2B1A97D465E9B0F5' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user THARE_AURA identified by values 'D82D34964FE26BFF' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user THARNESS_AURA identified by values '6A72421FE2326C3C' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user THILL1_AURA identified by values '462984BD9F3CCAAB' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user TLONG identified by values '810CA3A1D43E0B25' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user TMDUNGARE_AURA identified by values 'A6DEF6350EFCA390' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user TRIDGE_AURA identified by values '0E7159B022B1028E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user UVSCHEDULER identified by values '4CAB486961F07A50' default tablespace CFA temporary tablespace TEMP profile UVPROFILE account unlock;
create user UZAMIR_AURA identified by values 'E48FA3F6E489E6D9' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user VGIBSON_AURA identified by values 'B82A8EF94FE2087E' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user VKMOORE_AURA identified by values 'CBEA96D15F4B7E5A' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user VLING identified by values 'F508A44522EEB033' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user VPATEL1_AURA identified by values 'E891648A9E797307' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user VWILSON identified by values '6A096A53ADABC264' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user VWILSON_AURA identified by values 'D2FC4E7D45ADECB9' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user WARIF_AURA identified by values 'FE3D3242B53AC290' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user WEBSERVICE_USER identified by values 'C92A57490C178914' default tablespace CFA temporary tablespace TEMP profile DEFAULT account unlock;
create user WGOODENOUGH identified by values '94A29BBED0CB1992' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user WGOODENOUGH_AURA identified by values '330278888C7940C1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user WJGREEN_AURA identified by values 'E050675C5D417339' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user YLOWE identified by values '8426E3DBD7523B14' default tablespace USERS temporary tablespace TEMP profile APP_USER account unlock;
create user YSAWANT_AURA identified by values '4B3FAA1FBEFA9FD3' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ZAHMED_AURA identified by values '6D3CA454CB9519F1' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ZARIF_AURA identified by values '5972E6767144BDFE' default tablespace SYSTEM temporary tablespace TEMP profile DEFAULT account unlock;
create user ZNOAKE_AURA identified by values '016A1EF14F2A2544' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ZSAYED_AURA identified by values 'B9EDE7A4E42B9D56' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
create user ZTHOMPSON_AURA identified by values '542687EF0E4544C3' default tablespace CFA temporary tablespace TEMP profile APP_USER account unlock;
